import type { Skill, SkillId, ChordQuality, ScaleId } from '../../../shared/types/course.js';

export const welcome = {
  number: 0,
  name: 'Welcome',
  subtitle: 'Meet your ear-training tutor',
  label: 'Welcome',
} as const;

export const chapters = [
  {
    number: 1,
    name: 'Pitch & intervals',
    subtitle: 'Direction, distance, and reference notes',
    label: 'Foundations',
  },
  {
    number: 2,
    name: 'Triads & inversions',
    subtitle: 'Quality, bass position, and chord roots',
    label: 'Core harmony',
  },
  {
    number: 3,
    name: 'Scales & melodies',
    subtitle: 'Hear notes in a tonal context',
    label: 'Tonal hearing',
  },
  {
    number: 4,
    name: 'Sevenths & progressions',
    subtitle: 'Richer chords and harmonic movement',
    label: 'Harmonic hearing',
  },
  {
    number: 5,
    name: 'Extended harmony',
    subtitle: 'Added tones, extensions, and altered dominants',
    label: 'Advanced color',
  },
] as const;

export const skills: Skill[] = [
  {
    id: 'pitch-direction',
    name: 'Pitch direction',
    shortName: 'Pitch direction',
    chapter: 1,
    description: 'Find the motion between two notes.',
    objective: 'Hear upward or downward motion across changing registers.',
    prerequisites: [],
    difficulty: 1,
    symbol: '01',
  },
  {
    id: 'intervals-foundation',
    name: 'Intervals up & down',
    shortName: 'Intervals up & down',
    chapter: 1,
    description: 'Thirds, fourths, fifths, and octaves.',
    objective: 'Recognize rising or falling intervals across random roots and registers.',
    prerequisites: ['pitch-direction'],
    difficulty: 2,
    symbol: '02',
  },
  {
    id: 'intervals-harmonic',
    name: 'Intervals together',
    shortName: 'Intervals together',
    chapter: 1,
    description: 'The same five distances, with both notes sounding together.',
    objective: 'Recognize harmonic intervals across random roots and registers.',
    prerequisites: ['intervals-foundation'],
    difficulty: 2,
    symbol: '03',
  },
  {
    id: 'intervals-chromatic',
    name: 'Chromatic intervals',
    shortName: 'Chromatic intervals',
    chapter: 1,
    description: 'Every distance within the octave.',
    objective: 'Distinguish nearby interval colors without a fixed starting note.',
    prerequisites: ['intervals-harmonic'],
    difficulty: 3,
    symbol: '04',
  },
  {
    id: 'reference-pitch',
    name: 'Reference pitch',
    shortName: 'Reference pitch',
    chapter: 1,
    description: 'Name a note with C4 as your reference.',
    objective: 'Build relative pitch, not a test of untrained absolute pitch.',
    prerequisites: ['intervals-chromatic'],
    difficulty: 2,
    symbol: '05',
  },
  {
    id: 'triads',
    name: 'Major & minor',
    shortName: 'Major & minor',
    chapter: 2,
    description: 'Two foundational harmonic colors.',
    objective: 'Hear the third inside a chord across roots and registers.',
    prerequisites: ['intervals-foundation'],
    difficulty: 1,
    symbol: '06',
  },
  {
    id: 'triad-colors',
    name: 'Triad colors',
    shortName: 'Triad colors',
    chapter: 2,
    description: 'Diminished, augmented, and suspended.',
    objective: 'Distinguish triad qualities with the intended root supplied.',
    prerequisites: ['triads'],
    difficulty: 3,
    symbol: '07',
  },
  {
    id: 'triad-inversions',
    name: 'Triad inversions',
    shortName: 'Triad inversions',
    chapter: 2,
    description: 'One chord, three perspectives.',
    objective: 'Identify quality and the chord tone in the bass.',
    prerequisites: ['triads'],
    difficulty: 3,
    symbol: '08',
  },
  {
    id: 'chord-roots',
    name: 'Roots & quality',
    shortName: 'Roots & quality',
    chapter: 2,
    description: 'Root and quality, with a reference pitch.',
    objective: 'Combine relative root hearing with chord recognition.',
    prerequisites: ['reference-pitch', 'triads'],
    difficulty: 3,
    symbol: '09',
  },
  {
    id: 'scale-degrees',
    name: 'Scale degrees',
    shortName: 'Scale degrees',
    chapter: 3,
    description: 'Hear a note in relation to its key.',
    objective: 'Name scale degrees after a tonic-establishing cadence.',
    prerequisites: ['pitch-direction'],
    difficulty: 2,
    symbol: '10',
  },
  {
    id: 'scales',
    name: 'Scales',
    shortName: 'Scales',
    chapter: 3,
    description: 'Major, minor, pentatonic, and blues.',
    objective: 'Hear the pattern of steps, not a memorized key.',
    prerequisites: ['scale-degrees'],
    difficulty: 3,
    symbol: '11',
  },
  {
    id: 'modes',
    name: 'Modes',
    shortName: 'Modes',
    chapter: 3,
    description: 'Dorian, Lydian, and their neighbors.',
    objective: 'Hear a mode by its characteristic degrees and tonal center.',
    prerequisites: ['scales', 'intervals-chromatic'],
    difficulty: 4,
    symbol: '12',
  },
  {
    id: 'melodies',
    name: 'Melodic hearing',
    shortName: 'Melodic hearing',
    chapter: 3,
    description: 'Short, freshly generated musical phrases.',
    objective: 'Recall three to five scale degrees after a key-establishing cadence.',
    prerequisites: ['scale-degrees', 'intervals-foundation'],
    difficulty: 4,
    symbol: '13',
  },
  {
    id: 'seventh-chords',
    name: 'Seventh chords',
    shortName: 'Seventh chords',
    chapter: 4,
    description: 'Major, minor, and dominant sevenths.',
    objective: 'Hear the seventh as a distinct layer of harmonic information.',
    prerequisites: ['triads'],
    difficulty: 3,
    symbol: '14',
  },
  {
    id: 'seventh-colors',
    name: 'Seventh colors',
    shortName: 'Seventh colors',
    chapter: 4,
    description: 'Half-diminished, diminished, and minor-major.',
    objective: 'Separate the quality of the triad from the quality of the seventh.',
    prerequisites: ['seventh-chords', 'triad-colors'],
    difficulty: 4,
    symbol: '15',
  },
  {
    id: 'seventh-inversions',
    name: 'Seventh inversions',
    shortName: 'Seventh inversions',
    chapter: 4,
    description: 'Four chord tones, four bass positions.',
    objective: 'Name the seventh-chord quality and inversion.',
    prerequisites: ['seventh-chords', 'triad-inversions'],
    difficulty: 4,
    symbol: '16',
  },
  {
    id: 'progressions',
    name: 'Progressions',
    shortName: 'Progressions',
    chapter: 4,
    description: 'Hear where a sequence of chords goes.',
    objective: 'Identify three to five scale-degree functions in a major key.',
    prerequisites: ['scale-degrees', 'triads'],
    difficulty: 4,
    symbol: '17',
  },
  {
    id: 'jazz-progressions',
    name: 'Jazz progressions',
    shortName: 'Jazz progressions',
    chapter: 4,
    description: 'Seventh-chord movement and ii-V-I.',
    objective: 'Follow harmonic function with voiced seventh chords.',
    prerequisites: ['progressions', 'seventh-chords'],
    difficulty: 5,
    symbol: '18',
  },
  {
    id: 'added-tones',
    name: 'Added tones',
    shortName: 'Added tones',
    chapter: 5,
    description: 'Sixths and added seconds or ninths.',
    objective: 'Hear added color without assuming a seventh is present.',
    prerequisites: ['triad-colors', 'seventh-chords'],
    difficulty: 4,
    symbol: '19',
  },
  {
    id: 'extensions',
    name: 'Extensions',
    shortName: 'Extensions',
    chapter: 5,
    description: 'Ninths, elevenths, and thirteenths.',
    objective: 'Distinguish upper colors in intentionally specified voicings.',
    prerequisites: ['added-tones', 'seventh-chords'],
    difficulty: 5,
    symbol: '20',
  },
  {
    id: 'altered-dominants',
    name: 'Altered dominants',
    shortName: 'Altered dominants',
    chapter: 5,
    description: 'Altered fifths, ninths, and upper tensions.',
    objective: 'Identify the alteration, not just the dominant foundation.',
    prerequisites: ['extensions'],
    difficulty: 5,
    symbol: '21',
  },
];

export function getSkill(id: SkillId): Skill {
  const skill = skills.find((item) => item.id === id);
  if (!skill) throw new Error(`Unknown skill: ${id}`);
  return skill;
}

export const essentialIntervals = [3, 4, 5, 7, 12] as const;

export const intervalLessons = {
  'intervals-foundation': {
    distances: essentialIntervals,
    presentations: ['ascending', 'descending'],
  },
  'intervals-harmonic': {
    distances: essentialIntervals,
    presentations: ['together'],
  },
  'intervals-chromatic': {
    distances: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    presentations: ['ascending', 'descending', 'together'],
  },
} as const;

export const chordPools: Partial<Record<SkillId, readonly ChordQuality[]>> = {
  triads: ['major', 'minor'],
  'triad-colors': ['major', 'minor', 'diminished', 'augmented', 'sus2', 'sus4'],
  'triad-inversions': ['major', 'minor'],
  'chord-roots': ['major', 'minor'],
  'seventh-chords': ['major7', 'minor7', 'dominant7'],
  'seventh-colors': [
    'halfDiminished7',
    'diminished7',
    'minorMajor7',
    'major7',
    'minor7',
    'dominant7',
  ],
  'seventh-inversions': ['major7', 'minor7', 'dominant7', 'halfDiminished7'],
  'added-tones': ['major6', 'minor6', 'add2', 'add9', 'minorAdd9'],
  extensions: [
    'major9',
    'minor9',
    'dominant9',
    'dominant11',
    'minor11',
    'major13',
    'minor13',
    'dominant13',
  ],
  'altered-dominants': ['7b9', '7#9', '7b5', '7#5', '7#11', '7b13', '7alt'],
};

export const scalePools: Record<'scales' | 'modes', readonly ScaleId[]> = {
  scales: [
    'major',
    'naturalMinor',
    'harmonicMinor',
    'melodicMinor',
    'majorPentatonic',
    'minorPentatonic',
    'blues',
  ],
  modes: ['dorian', 'phrygian', 'lydian', 'mixolydian', 'locrian', 'wholeTone'],
};
